# Generated by Django 4.2.4 on 2023-10-23 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bomberos', '0002_maquinaria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maquinaria',
            old_name='idUsuario',
            new_name='id',
        ),
    ]
