# Generated by Django 4.2.4 on 2023-10-23 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bomberos', '0003_rename_idusuario_maquinaria_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maquinaria',
            old_name='id',
            new_name='idUsuario',
        ),
    ]
