# Generated by Django 4.2.4 on 2023-10-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bomberos', '0004_rename_id_maquinaria_idusuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maquinaria',
            old_name='NombreProducto',
            new_name='Elemento',
        ),
        migrations.AddField(
            model_name='maquinaria',
            name='Marca',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maquinaria',
            name='observacion',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
