# Generated by Django 4.2.4 on 2023-10-23 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bomberos', '0005_rename_nombreproducto_maquinaria_elemento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maquinaria',
            old_name='CantidadProducto',
            new_name='Cantidad',
        ),
    ]
