# Generated by Django 4.2.4 on 2023-10-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bomberos', '0006_rename_cantidadproducto_maquinaria_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinaria',
            name='Imagen',
            field=models.ImageField(upload_to='maquinaria_images/'),
        ),
    ]
