# Generated by Django 4.2.4 on 2023-10-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bomberos', '0009_alter_maquinaria_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maquinaria',
            old_name='IdMaquinaria',
            new_name='CodigoElementos',
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='Imagen',
            field=models.ImageField(upload_to='maquinaria_images/'),
        ),
    ]
