# Generated by Django 4.2.4 on 2023-10-24 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bomberos', '0011_areasalud_rename_mantencion_maquinaria_mantencion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='IdMaquinaria',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='idAreaSalud',
        ),
        migrations.DeleteModel(
            name='AreaSalud',
        ),
        migrations.DeleteModel(
            name='Prestamo',
        ),
    ]
