# Generated by Django 4.2.4 on 2023-10-24 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bomberos', '0013_areasalud_prestamo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='Estado',
            field=models.CharField(choices=[('prestado', 'Prestado'), ('entregado', 'Entregado'), ('no_entregado', 'No Entregado'), ('perdido', 'Perdido')], default='prestado', max_length=255),
        ),
    ]
